version: "3"

services:
  whoami:
    image: containous/whoami
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - traefik.frontend.rule=Host:whoami.example.com
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https

networks:
  traefik-public:
    external: true
