version: "3"

services:
  whoami:
    image: containous/whoami # A container that exposes an API to show its IP address
    networks:
      - default
      - whoami-public
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.frontend.rule=Host:whoami.example.com
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https
        - traefik.tags=traefik-public
        - traefik.docker.network=whoami-public

networks:
  whoami-public:
    external: true
