Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    (0..1).each do |i|
        config.vm.define "node#{i}" do |node|
            node.vm.box = "ubuntu/xenial64"
            node.vm.hostname = "node#{i}"
            node.vm.network "private_network", ip: "192.168.60.#{i + 10}", netmask: "255.255.255.0"
            node.vm.provider "virtualbox" do |v|
                v.name = "node#{i}"
                v.memory = 1024
                v.gui = false
            end        
            node.vm.provision :shell, inline: "sed 's/127\.0\.1\.1.*node.*/192\.168\.60\.#{i + 10} node#{i}/' -i /etc/hosts"
        end
    end
end