version: "3"

services:
  app1-v1:
    build: ./app1
    env_file:
      - ./app.env
    networks:
      appnet:
        aliases:
          - app2
    environment:
      - SERVICE_NAME=app1
      - SERVICE_TAGS=version|v1
      - SERVICE_PROTOCOL=http
  app2:
    build: ./app2
    env_file:
      - ./app.env
    networks:
      appnet:
        aliases:
          - app1
  gw1:
    build: ./gw1
    env_file:
      - ./app.env
    ports:
      - 9001:3000
    networks:
      - appnet
  gw2:
    build: ./gw2
    env_file:
      - ./app.env
    ports:
      - 9002:3000
    networks:
      - appnet
networks:
  appnet:
